CREATE TABLE quotes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    text NVARCHAR(1000) NOT NULL,
    author NVARCHAR(40) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    likes INT NOT NULL DEFAULT 0,
    dislikes INT NOT NULL DEFAULT 0
);