version: "3.7"

volumes:
    db_data:

networks:
    db_net:

services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: quotes
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - db_net
        ports:
            - "3306:3306"
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-uroot", "-proot" ]
            interval: 3s
            timeout: 3s
            retries: 10
    app:
        build: .
        ports:
            - "8080:8080"
        networks:
            - db_net
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: quotes
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
            interval: 3s
            timeout: 3s
            retries: 10