version: "3.7"

volumes:
    db_data:

networks:
    db_net:

services:
    db:
        build:
            context: .
            dockerfile: ./db.Dockerfile
            args:
                DB_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - db_net
        ports:
            - "3306:3306"
    api:
        build: .
        ports:
            - "8080:8080"
        networks:
            - db_net
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: quotes